// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, event_id, total_amount, status, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, event_id, total_amount, status, expires_at, created_at, updated_at
`

type CreateOrderParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	EventID     uuid.UUID      `json:"event_id"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	Status      string         `json:"status"`
	ExpiresAt   time.Time      `json:"expires_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.EventID,
		arg.TotalAmount,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, ticket_type_id, quantity, price, subtotal)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, ticket_type_id, quantity, price, subtotal
`

type CreateOrderItemParams struct {
	OrderID      uuid.UUID      `json:"order_id"`
	TicketTypeID uuid.UUID      `json:"ticket_type_id"`
	Quantity     int32          `json:"quantity"`
	Price        pgtype.Numeric `json:"price"`
	Subtotal     pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.Price,
		arg.Subtotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.Price,
		&i.Subtotal,
	)
	return i, err
}

const getDailySalesTrend = `-- name: GetDailySalesTrend :many
SELECT 
    DATE(created_at) as sale_date,
    COALESCE(SUM(total_amount), 0)::numeric as total_revenue,
    COALESCE(SUM((SELECT SUM(quantity) FROM order_items WHERE order_items.order_id = orders.id)), 0)::bigint as tickets_sold
FROM orders 
WHERE event_id = ANY($1::uuid[]) AND status = 'SUKSES'
  AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(created_at)
ORDER BY sale_date ASC
`

type GetDailySalesTrendRow struct {
	SaleDate     pgtype.Date    `json:"sale_date"`
	TotalRevenue pgtype.Numeric `json:"total_revenue"`
	TicketsSold  int64          `json:"tickets_sold"`
}

func (q *Queries) GetDailySalesTrend(ctx context.Context, dollar_1 []uuid.UUID) ([]GetDailySalesTrendRow, error) {
	rows, err := q.db.Query(ctx, getDailySalesTrend, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySalesTrendRow{}
	for rows.Next() {
		var i GetDailySalesTrendRow
		if err := rows.Scan(&i.SaleDate, &i.TotalRevenue, &i.TicketsSold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPendingOrders = `-- name: GetExpiredPendingOrders :many
SELECT id, user_id, event_id, total_amount, status, expires_at, created_at, updated_at FROM orders WHERE status = 'PENDING' AND expires_at < NOW()
`

func (q *Queries) GetExpiredPendingOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getExpiredPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, event_id, total_amount, status, expires_at, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizerStats = `-- name: GetOrganizerStats :one
SELECT 
    COALESCE(COUNT(DISTINCT id), 0)::bigint as total_orders,
    COALESCE(SUM(total_amount), 0)::numeric as total_revenue,
    COALESCE(SUM((SELECT SUM(quantity) FROM order_items WHERE order_items.order_id = orders.id)), 0)::bigint as tickets_sold
FROM orders 
WHERE event_id = ANY($1::uuid[]) AND status = 'SUKSES'
`

type GetOrganizerStatsRow struct {
	TotalOrders  int64          `json:"total_orders"`
	TotalRevenue pgtype.Numeric `json:"total_revenue"`
	TicketsSold  int64          `json:"tickets_sold"`
}

func (q *Queries) GetOrganizerStats(ctx context.Context, dollar_1 []uuid.UUID) (GetOrganizerStatsRow, error) {
	row := q.db.QueryRow(ctx, getOrganizerStats, dollar_1)
	var i GetOrganizerStatsRow
	err := row.Scan(&i.TotalOrders, &i.TotalRevenue, &i.TicketsSold)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, ticket_type_id, quantity, price, subtotal FROM order_items WHERE order_id = $1
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.Price,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByEvents = `-- name: ListOrdersByEvents :many
SELECT id, user_id, event_id, total_amount, status, expires_at, created_at, updated_at FROM orders 
WHERE event_id = ANY($1::uuid[])
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type ListOrdersByEventsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListOrdersByEvents(ctx context.Context, arg ListOrdersByEventsParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByEvents, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, event_id, total_amount, status, expires_at, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, event_id, total_amount, status, expires_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
