// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (order_id, user_id, event_id, ticket_type_id, ticket_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, user_id, event_id, ticket_type_id, ticket_code, status, created_at, updated_at
`

type CreateTicketParams struct {
	OrderID      uuid.UUID `json:"order_id"`
	UserID       uuid.UUID `json:"user_id"`
	EventID      uuid.UUID `json:"event_id"`
	TicketTypeID uuid.UUID `json:"ticket_type_id"`
	TicketCode   string    `json:"ticket_code"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.OrderID,
		arg.UserID,
		arg.EventID,
		arg.TicketTypeID,
		arg.TicketCode,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.TicketCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, order_id, user_id, event_id, ticket_type_id, ticket_code, status, created_at, updated_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.TicketCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByCode = `-- name: GetTicketByCode :one
SELECT id, order_id, user_id, event_id, ticket_type_id, ticket_code, status, created_at, updated_at FROM tickets WHERE ticket_code = $1
`

func (q *Queries) GetTicketByCode(ctx context.Context, ticketCode string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByCode, ticketCode)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.TicketCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketsByEvent = `-- name: ListTicketsByEvent :many
SELECT id, order_id, user_id, event_id, ticket_type_id, ticket_code, status, created_at, updated_at FROM tickets WHERE event_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTicketsByEvent(ctx context.Context, eventID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.TicketCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByOrder = `-- name: ListTicketsByOrder :many
SELECT id, order_id, user_id, event_id, ticket_type_id, ticket_code, status, created_at, updated_at FROM tickets WHERE order_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTicketsByOrder(ctx context.Context, orderID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.TicketCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUser = `-- name: ListTicketsByUser :many
SELECT id, order_id, user_id, event_id, ticket_type_id, ticket_code, status, created_at, updated_at FROM tickets WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTicketsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTicketsByUser(ctx context.Context, arg ListTicketsByUserParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.EventID,
			&i.TicketTypeID,
			&i.TicketCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, order_id, user_id, event_id, ticket_type_id, ticket_code, status, created_at, updated_at
`

type UpdateTicketStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.ID, arg.Status)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.EventID,
		&i.TicketTypeID,
		&i.TicketCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
