// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: withdrawals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (
    organizer_id,
    amount,
    bank_name,
    account_number,
    account_name,
    notes,
    status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organizer_id, amount, bank_name, account_number, account_name, status, rejection_reason, notes, created_at, updated_at
`

type CreateWithdrawalParams struct {
	OrganizerID   uuid.UUID      `json:"organizer_id"`
	Amount        pgtype.Numeric `json:"amount"`
	BankName      string         `json:"bank_name"`
	AccountNumber string         `json:"account_number"`
	AccountName   string         `json:"account_name"`
	Notes         pgtype.Text    `json:"notes"`
	Status        string         `json:"status"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal,
		arg.OrganizerID,
		arg.Amount,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountName,
		arg.Notes,
		arg.Status,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Amount,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountName,
		&i.Status,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalWithdrawnByOrganizer = `-- name: GetTotalWithdrawnByOrganizer :one
SELECT 
    COALESCE(SUM(amount), 0)::numeric as total_withdrawn
FROM withdrawals
WHERE organizer_id = $1
  AND status IN ('PENDING', 'APPROVED', 'PAID')
`

func (q *Queries) GetTotalWithdrawnByOrganizer(ctx context.Context, organizerID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalWithdrawnByOrganizer, organizerID)
	var total_withdrawn pgtype.Numeric
	err := row.Scan(&total_withdrawn)
	return total_withdrawn, err
}

const getWithdrawal = `-- name: GetWithdrawal :one
SELECT id, organizer_id, amount, bank_name, account_number, account_name, status, rejection_reason, notes, created_at, updated_at FROM withdrawals
WHERE id = $1
`

func (q *Queries) GetWithdrawal(ctx context.Context, id uuid.UUID) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawal, id)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Amount,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountName,
		&i.Status,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawnSummaryByOrganizer = `-- name: GetWithdrawnSummaryByOrganizer :one
SELECT 
    COALESCE(SUM(CASE WHEN status IN ('PENDING', 'APPROVED', 'PAID') THEN amount ELSE 0 END), 0)::numeric as total_deducted,
    COALESCE(SUM(CASE WHEN status = 'PENDING' THEN amount ELSE 0 END), 0)::numeric as pending_amount,
    COALESCE(SUM(CASE WHEN status = 'PAID' THEN amount ELSE 0 END), 0)::numeric as paid_amount,
    COALESCE(COUNT(*), 0)::bigint as total_requests
FROM withdrawals
WHERE organizer_id = $1
`

type GetWithdrawnSummaryByOrganizerRow struct {
	TotalDeducted pgtype.Numeric `json:"total_deducted"`
	PendingAmount pgtype.Numeric `json:"pending_amount"`
	PaidAmount    pgtype.Numeric `json:"paid_amount"`
	TotalRequests int64          `json:"total_requests"`
}

func (q *Queries) GetWithdrawnSummaryByOrganizer(ctx context.Context, organizerID uuid.UUID) (GetWithdrawnSummaryByOrganizerRow, error) {
	row := q.db.QueryRow(ctx, getWithdrawnSummaryByOrganizer, organizerID)
	var i GetWithdrawnSummaryByOrganizerRow
	err := row.Scan(
		&i.TotalDeducted,
		&i.PendingAmount,
		&i.PaidAmount,
		&i.TotalRequests,
	)
	return i, err
}

const listAllWithdrawals = `-- name: ListAllWithdrawals :many
SELECT id, organizer_id, amount, bank_name, account_number, account_name, status, rejection_reason, notes, created_at, updated_at FROM withdrawals
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllWithdrawalsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllWithdrawals(ctx context.Context, arg ListAllWithdrawalsParams) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, listAllWithdrawals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Amount,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountName,
			&i.Status,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByOrganizer = `-- name: ListWithdrawalsByOrganizer :many
SELECT id, organizer_id, amount, bank_name, account_number, account_name, status, rejection_reason, notes, created_at, updated_at FROM withdrawals
WHERE organizer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWithdrawalsByOrganizerParams struct {
	OrganizerID uuid.UUID `json:"organizer_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListWithdrawalsByOrganizer(ctx context.Context, arg ListWithdrawalsByOrganizerParams) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsByOrganizer, arg.OrganizerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Amount,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountName,
			&i.Status,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByStatus = `-- name: ListWithdrawalsByStatus :many
SELECT id, organizer_id, amount, bank_name, account_number, account_name, status, rejection_reason, notes, created_at, updated_at FROM withdrawals
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWithdrawalsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListWithdrawalsByStatus(ctx context.Context, arg ListWithdrawalsByStatusParams) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Amount,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountName,
			&i.Status,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWithdrawalStatus = `-- name: UpdateWithdrawalStatus :one
UPDATE withdrawals
SET 
    status = $2,
    rejection_reason = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organizer_id, amount, bank_name, account_number, account_name, status, rejection_reason, notes, created_at, updated_at
`

type UpdateWithdrawalStatusParams struct {
	ID              uuid.UUID   `json:"id"`
	Status          string      `json:"status"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) UpdateWithdrawalStatus(ctx context.Context, arg UpdateWithdrawalStatusParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, updateWithdrawalStatus, arg.ID, arg.Status, arg.RejectionReason)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Amount,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountName,
		&i.Status,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
