// Code generated by sqlc. DO NOT EDIT.
// This is a stub file for compilation. Run `sqlc generate` to generate the real code.

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	Role         string      `json:"role"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	IsVerified   bool        `json:"is_verified"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Token     string      `json:"token"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress pgtype.Text `json:"ip_address"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
}
