// Code generated by sqlc. DO NOT EDIT.
// This is a stub file for compilation. Run `sqlc generate` to generate the real code.

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Token     string      `json:"token"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress pgtype.Text `json:"ip_address"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO refresh_tokens (user_id, token, user_agent, ip_address, expires_at) VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, token, user_agent, ip_address, expires_at, created_at`,
		arg.UserID, arg.Token, arg.UserAgent, arg.IpAddress, arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(&i.ID, &i.UserID, &i.Token, &i.UserAgent, &i.IpAddress, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, `SELECT id, user_id, token, user_agent, ip_address, expires_at, created_at FROM refresh_tokens WHERE token = $1 AND expires_at > NOW()`, token)
	var i RefreshToken
	err := row.Scan(&i.ID, &i.UserID, &i.Token, &i.UserAgent, &i.IpAddress, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, `DELETE FROM refresh_tokens WHERE token = $1`, token)
	return err
}

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, `DELETE FROM refresh_tokens WHERE user_id = $1`, userID)
	return err
}

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, `DELETE FROM refresh_tokens WHERE expires_at <= NOW()`)
	return err
}
