// Code generated by sqlc. DO NOT EDIT.
// This is a stub file for compilation. Run `sqlc generate` to generate the real code.

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO users (email, password_hash, full_name, phone, role) VALUES ($1, $2, $3, $4, $5) RETURNING id, email, password_hash, full_name, phone, role, avatar_url, is_verified, is_active, created_at, updated_at`,
		arg.Email, arg.PasswordHash, arg.FullName, arg.Phone, arg.Role,
	)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.FullName, &i.Phone, &i.Role, &i.AvatarUrl, &i.IsVerified, &i.IsActive, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, `SELECT id, email, password_hash, full_name, phone, role, avatar_url, is_verified, is_active, created_at, updated_at FROM users WHERE id = $1 AND is_active = TRUE`, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.FullName, &i.Phone, &i.Role, &i.AvatarUrl, &i.IsVerified, &i.IsActive, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, `SELECT id, email, password_hash, full_name, phone, role, avatar_url, is_verified, is_active, created_at, updated_at FROM users WHERE email = $1 AND is_active = TRUE`, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.FullName, &i.Phone, &i.Role, &i.AvatarUrl, &i.IsVerified, &i.IsActive, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

type UpdateUserProfileParams struct {
	ID        uuid.UUID   `json:"id"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE users SET full_name = $2, phone = $3, avatar_url = $4, updated_at = NOW() WHERE id = $1 AND is_active = TRUE RETURNING id, email, password_hash, full_name, phone, role, avatar_url, is_verified, is_active, created_at, updated_at`,
		arg.ID, arg.FullName, arg.Phone, arg.AvatarUrl,
	)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.FullName, &i.Phone, &i.Role, &i.AvatarUrl, &i.IsVerified, &i.IsActive, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) UpdateUserPassword(ctx context.Context, id uuid.UUID, passwordHash string) error {
	_, err := q.db.Exec(ctx, `UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1`, id, passwordHash)
	return err
}

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `UPDATE users SET is_active = FALSE, updated_at = NOW() WHERE id = $1`, id)
	return err
}

func (q *Queries) ListUsers(ctx context.Context, limit int32, offset int32) ([]User, error) {
	rows, err := q.db.Query(ctx, `SELECT id, email, password_hash, full_name, phone, role, avatar_url, is_verified, is_active, created_at, updated_at FROM users WHERE is_active = TRUE ORDER BY created_at DESC LIMIT $1 OFFSET $2`, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.FullName, &i.Phone, &i.Role, &i.AvatarUrl, &i.IsVerified, &i.IsActive, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, `SELECT COUNT(*) FROM users WHERE is_active = TRUE`)
	var count int64
	err := row.Scan(&count)
	return count, err
}
