// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashless.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTopup = `-- name: CreateTopup :one
INSERT INTO topups (wallet_id, amount, status) VALUES ($1, $2, $3) RETURNING id, wallet_id, amount, status, created_at, updated_at
`

type CreateTopupParams struct {
	WalletID uuid.UUID      `json:"wallet_id"`
	Amount   pgtype.Numeric `json:"amount"`
	Status   string         `json:"status"`
}

func (q *Queries) CreateTopup(ctx context.Context, arg CreateTopupParams) (Topup, error) {
	row := q.db.QueryRow(ctx, createTopup, arg.WalletID, arg.Amount, arg.Status)
	var i Topup
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (wallet_id, type, amount, merchant_id, description) VALUES ($1, $2, $3, $4, $5) RETURNING id, wallet_id, type, amount, merchant_id, description, created_at
`

type CreateTransactionParams struct {
	WalletID    uuid.UUID      `json:"wallet_id"`
	Type        string         `json:"type"`
	Amount      pgtype.Numeric `json:"amount"`
	MerchantID  pgtype.UUID    `json:"merchant_id"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WalletID,
		arg.Type,
		arg.Amount,
		arg.MerchantID,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.MerchantID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id) VALUES ($1) RETURNING id, user_id, balance, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductWalletBalance = `-- name: DeductWalletBalance :one
UPDATE wallets SET balance = balance - $2, updated_at = NOW() WHERE id = $1 AND balance >= $2 RETURNING id, user_id, balance, created_at, updated_at
`

type DeductWalletBalanceParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) DeductWalletBalance(ctx context.Context, arg DeductWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, deductWalletBalance, arg.ID, arg.Balance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopup = `-- name: GetTopup :one
SELECT id, wallet_id, amount, status, created_at, updated_at FROM topups WHERE id = $1
`

func (q *Queries) GetTopup(ctx context.Context, id uuid.UUID) (Topup, error) {
	row := q.db.QueryRow(ctx, getTopup, id)
	var i Topup
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, user_id, balance, created_at, updated_at FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, wallet_id, type, amount, merchant_id, description, created_at FROM transactions WHERE wallet_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	WalletID uuid.UUID `json:"wallet_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.MerchantID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopupStatus = `-- name: UpdateTopupStatus :one
UPDATE topups SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, wallet_id, amount, status, created_at, updated_at
`

type UpdateTopupStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTopupStatus(ctx context.Context, arg UpdateTopupStatusParams) (Topup, error) {
	row := q.db.QueryRow(ctx, updateTopupStatus, arg.ID, arg.Status)
	var i Topup
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE wallets SET balance = balance + $2, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, balance, created_at, updated_at
`

type UpdateWalletBalanceParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.ID, arg.Balance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
