// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTopup(ctx context.Context, arg CreateTopupParams) (Topup, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error)
	DeductWalletBalance(ctx context.Context, arg DeductWalletBalanceParams) (Wallet, error)
	GetTopup(ctx context.Context, id uuid.UUID) (Topup, error)
	GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	UpdateTopupStatus(ctx context.Context, arg UpdateTopupStatusParams) (Topup, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
