// Code generated by sqlc. DO NOT EDIT.
// source: gate.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLocalTicket = `-- name: CreateLocalTicket :one
INSERT INTO local_tickets (id, ticket_code, status)
VALUES ($1, $2, $3)
RETURNING id, ticket_code, status
`

type CreateLocalTicketParams struct {
	ID         uuid.UUID `json:"id"`
	TicketCode string    `json:"ticket_code"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateLocalTicket(ctx context.Context, arg CreateLocalTicketParams) (LocalTicket, error) {
	row := q.db.QueryRow(ctx, createLocalTicket, arg.ID, arg.TicketCode, arg.Status)
	var i LocalTicket
	err := row.Scan(&i.ID, &i.TicketCode, &i.Status)
	return i, err
}

const getLocalTicketByCode = `-- name: GetLocalTicketByCode :one
SELECT id, ticket_code, status FROM local_tickets WHERE ticket_code = $1
`

func (q *Queries) GetLocalTicketByCode(ctx context.Context, ticketCode string) (LocalTicket, error) {
	row := q.db.QueryRow(ctx, getLocalTicketByCode, ticketCode)
	var i LocalTicket
	err := row.Scan(&i.ID, &i.TicketCode, &i.Status)
	return i, err
}

const getLocalTicketByID = `-- name: GetLocalTicketByID :one
SELECT id, ticket_code, status FROM local_tickets WHERE id = $1
`

func (q *Queries) GetLocalTicketByID(ctx context.Context, id uuid.UUID) (LocalTicket, error) {
	row := q.db.QueryRow(ctx, getLocalTicketByID, id)
	var i LocalTicket
	err := row.Scan(&i.ID, &i.TicketCode, &i.Status)
	return i, err
}

const updateLocalTicketStatus = `-- name: UpdateLocalTicketStatus :one
UPDATE local_tickets SET status = $2 WHERE id = $1 RETURNING id, ticket_code, status
`

type UpdateLocalTicketStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLocalTicketStatus(ctx context.Context, arg UpdateLocalTicketStatusParams) (LocalTicket, error) {
	row := q.db.QueryRow(ctx, updateLocalTicketStatus, arg.ID, arg.Status)
	var i LocalTicket
	err := row.Scan(&i.ID, &i.TicketCode, &i.Status)
	return i, err
}
