// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LocalTicket struct {
	ID         pgtype.UUID `json:"id"`
	EventID    pgtype.UUID `json:"event_id"`
	TicketCode string      `json:"ticket_code"`
	Status     string      `json:"status"`
}
