// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"github.com/google/uuid"
)

type LocalTicket struct {
	ID         uuid.UUID `json:"id"`
	TicketCode string    `json:"ticket_code"`
	Status     string    `json:"status"`
}
