// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLocalTicket(ctx context.Context, arg CreateLocalTicketParams) (LocalTicket, error)
	GetLocalTicketByCode(ctx context.Context, ticketCode string) (LocalTicket, error)
	GetLocalTicketByID(ctx context.Context, id pgtype.UUID) (LocalTicket, error)
	UpdateLocalTicketStatus(ctx context.Context, arg UpdateLocalTicketStatusParams) (LocalTicket, error)
}

var _ Querier = (*Queries)(nil)
