// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByOrganizer = `-- name: CountEventsByOrganizer :one
SELECT COUNT(*) FROM events WHERE organizer_id = $1
`

func (q *Queries) CountEventsByOrganizer(ctx context.Context, organizerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByOrganizer, organizerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedEvents = `-- name: CountPublishedEvents :one
SELECT COUNT(*) FROM events WHERE status = 'published'
`

func (q *Queries) CountPublishedEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    organizer_id, venue_id, category_id, title, slug, description,
    banner_url, start_date, end_date, status, is_online, online_url, max_attendees
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at
`

type CreateEventParams struct {
	OrganizerID  pgtype.UUID        `json:"organizer_id"`
	VenueID      pgtype.UUID        `json:"venue_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	BannerUrl    pgtype.Text        `json:"banner_url"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	EndDate      pgtype.Timestamptz `json:"end_date"`
	Status       string             `json:"status"`
	IsOnline     bool               `json:"is_online"`
	OnlineUrl    pgtype.Text        `json:"online_url"`
	MaxAttendees pgtype.Int4        `json:"max_attendees"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizerID,
		arg.VenueID,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.BannerUrl,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.IsOnline,
		arg.OnlineUrl,
		arg.MaxAttendees,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.VenueID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.MaxAttendees,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1 AND organizer_id = $2
`

type DeleteEventParams struct {
	ID          pgtype.UUID `json:"id"`
	OrganizerID pgtype.UUID `json:"organizer_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.OrganizerID)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.VenueID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.MaxAttendees,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at FROM events WHERE slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.VenueID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.MaxAttendees,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventIDsByOrganizer = `-- name: ListEventIDsByOrganizer :many
SELECT id FROM events WHERE organizer_id = $1
`

func (q *Queries) ListEventIDsByOrganizer(ctx context.Context, organizerID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listEventIDsByOrganizer, organizerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at FROM events
WHERE status = 'published'
ORDER BY start_date ASC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.VenueID,
			&i.CategoryID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.BannerUrl,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.MaxAttendees,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCategory = `-- name: ListEventsByCategory :many
SELECT id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at FROM events
WHERE category_id = $1 AND status = 'published'
ORDER BY start_date ASC
LIMIT $2 OFFSET $3
`

type ListEventsByCategoryParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListEventsByCategory(ctx context.Context, arg ListEventsByCategoryParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.VenueID,
			&i.CategoryID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.BannerUrl,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.MaxAttendees,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByOrganizer = `-- name: ListEventsByOrganizer :many
SELECT id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at FROM events
WHERE organizer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsByOrganizerParams struct {
	OrganizerID pgtype.UUID `json:"organizer_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListEventsByOrganizer(ctx context.Context, arg ListEventsByOrganizerParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrganizer, arg.OrganizerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.VenueID,
			&i.CategoryID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.BannerUrl,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.MaxAttendees,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEvents = `-- name: SearchEvents :many
SELECT id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at FROM events
WHERE status = 'published'
  AND (title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
ORDER BY start_date ASC
LIMIT $2 OFFSET $3
`

type SearchEventsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchEvents, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.VenueID,
			&i.CategoryID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.BannerUrl,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.IsOnline,
			&i.OnlineUrl,
			&i.MaxAttendees,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    venue_id = $2, category_id = $3, title = $4, slug = $5,
    description = $6, banner_url = $7, start_date = $8, end_date = $9,
    status = $10, is_online = $11, online_url = $12, max_attendees = $13,
    updated_at = NOW()
WHERE id = $1 AND organizer_id = $14
RETURNING id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at
`

type UpdateEventParams struct {
	ID           pgtype.UUID        `json:"id"`
	VenueID      pgtype.UUID        `json:"venue_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	BannerUrl    pgtype.Text        `json:"banner_url"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	EndDate      pgtype.Timestamptz `json:"end_date"`
	Status       string             `json:"status"`
	IsOnline     bool               `json:"is_online"`
	OnlineUrl    pgtype.Text        `json:"online_url"`
	MaxAttendees pgtype.Int4        `json:"max_attendees"`
	OrganizerID  pgtype.UUID        `json:"organizer_id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.VenueID,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.BannerUrl,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.IsOnline,
		arg.OnlineUrl,
		arg.MaxAttendees,
		arg.OrganizerID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.VenueID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.MaxAttendees,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventStatus = `-- name: UpdateEventStatus :one
UPDATE events SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organizer_id, venue_id, category_id, title, slug, description, banner_url, start_date, end_date, status, is_online, online_url, max_attendees, created_at, updated_at
`

type UpdateEventStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventStatus, arg.ID, arg.Status)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.VenueID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsOnline,
		&i.OnlineUrl,
		&i.MaxAttendees,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
