// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Icon      pgtype.Text        `json:"icon"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID           pgtype.UUID        `json:"id"`
	OrganizerID  pgtype.UUID        `json:"organizer_id"`
	VenueID      pgtype.UUID        `json:"venue_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	BannerUrl    pgtype.Text        `json:"banner_url"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	EndDate      pgtype.Timestamptz `json:"end_date"`
	Status       string             `json:"status"`
	IsOnline     bool               `json:"is_online"`
	OnlineUrl    pgtype.Text        `json:"online_url"`
	MaxAttendees pgtype.Int4        `json:"max_attendees"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TicketType struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	Quantity    int32              `json:"quantity"`
	Sold        int32              `json:"sold"`
	MaxPerOrder pgtype.Int4        `json:"max_per_order"`
	SaleStart   pgtype.Timestamptz `json:"sale_start"`
	SaleEnd     pgtype.Timestamptz `json:"sale_end"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Venue struct {
	ID          pgtype.UUID        `json:"id"`
	OrganizerID pgtype.UUID        `json:"organizer_id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	City        string             `json:"city"`
	Province    pgtype.Text        `json:"province"`
	Country     string             `json:"country"`
	Latitude    pgtype.Numeric     `json:"latitude"`
	Longitude   pgtype.Numeric     `json:"longitude"`
	Capacity    pgtype.Int4        `json:"capacity"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
