// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountEventsByOrganizer(ctx context.Context, organizerID pgtype.UUID) (int64, error)
	CountPublishedEvents(ctx context.Context) (int64, error)
	CountVenues(ctx context.Context) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	DecrementTicketSold(ctx context.Context, arg DecrementTicketSoldParams) (TicketType, error)
	DeleteEvent(ctx context.Context, arg DeleteEventParams) error
	DeleteTicketType(ctx context.Context, id pgtype.UUID) error
	DeleteVenue(ctx context.Context, arg DeleteVenueParams) error
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	GetEventBySlug(ctx context.Context, slug string) (Event, error)
	GetTicketTypeByID(ctx context.Context, id pgtype.UUID) (TicketType, error)
	GetVenueByID(ctx context.Context, id pgtype.UUID) (Venue, error)
	IncrementTicketSold(ctx context.Context, arg IncrementTicketSoldParams) (TicketType, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListEventIDsByOrganizer(ctx context.Context, organizerID pgtype.UUID) ([]pgtype.UUID, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsByCategory(ctx context.Context, arg ListEventsByCategoryParams) ([]Event, error)
	ListEventsByOrganizer(ctx context.Context, arg ListEventsByOrganizerParams) ([]Event, error)
	ListTicketTypesByEvent(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error)
	ListVenues(ctx context.Context, arg ListVenuesParams) ([]Venue, error)
	ListVenuesByOrganizer(ctx context.Context, arg ListVenuesByOrganizerParams) ([]Venue, error)
	SearchEvents(ctx context.Context, arg SearchEventsParams) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error)
	UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) (TicketType, error)
	UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error)
}

var _ Querier = (*Queries)(nil)
