// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVenues = `-- name: CountVenues :one
SELECT COUNT(*) FROM venues
`

func (q *Queries) CountVenues(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVenues)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    organizer_id, name, address, city, province, country,
    latitude, longitude, capacity, description
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organizer_id, name, address, city, province, country, latitude, longitude, capacity, description, created_at, updated_at
`

type CreateVenueParams struct {
	OrganizerID pgtype.UUID    `json:"organizer_id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        string         `json:"city"`
	Province    pgtype.Text    `json:"province"`
	Country     string         `json:"country"`
	Latitude    pgtype.Numeric `json:"latitude"`
	Longitude   pgtype.Numeric `json:"longitude"`
	Capacity    pgtype.Int4    `json:"capacity"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.OrganizerID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Province,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.Capacity,
		arg.Description,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Province,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Capacity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues WHERE id = $1 AND organizer_id = $2
`

type DeleteVenueParams struct {
	ID          pgtype.UUID `json:"id"`
	OrganizerID pgtype.UUID `json:"organizer_id"`
}

func (q *Queries) DeleteVenue(ctx context.Context, arg DeleteVenueParams) error {
	_, err := q.db.Exec(ctx, deleteVenue, arg.ID, arg.OrganizerID)
	return err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, organizer_id, name, address, city, province, country, latitude, longitude, capacity, description, created_at, updated_at FROM venues WHERE id = $1
`

func (q *Queries) GetVenueByID(ctx context.Context, id pgtype.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Province,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Capacity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, organizer_id, name, address, city, province, country, latitude, longitude, capacity, description, created_at, updated_at FROM venues
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListVenuesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVenues(ctx context.Context, arg ListVenuesParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Province,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Capacity,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesByOrganizer = `-- name: ListVenuesByOrganizer :many
SELECT id, organizer_id, name, address, city, province, country, latitude, longitude, capacity, description, created_at, updated_at FROM venues
WHERE organizer_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListVenuesByOrganizerParams struct {
	OrganizerID pgtype.UUID `json:"organizer_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListVenuesByOrganizer(ctx context.Context, arg ListVenuesByOrganizerParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesByOrganizer, arg.OrganizerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Province,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Capacity,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues SET
    name = $2, address = $3, city = $4, province = $5, country = $6,
    latitude = $7, longitude = $8, capacity = $9, description = $10,
    updated_at = NOW()
WHERE id = $1 AND organizer_id = $11
RETURNING id, organizer_id, name, address, city, province, country, latitude, longitude, capacity, description, created_at, updated_at
`

type UpdateVenueParams struct {
	ID          pgtype.UUID    `json:"id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	City        string         `json:"city"`
	Province    pgtype.Text    `json:"province"`
	Country     string         `json:"country"`
	Latitude    pgtype.Numeric `json:"latitude"`
	Longitude   pgtype.Numeric `json:"longitude"`
	Capacity    pgtype.Int4    `json:"capacity"`
	Description pgtype.Text    `json:"description"`
	OrganizerID pgtype.UUID    `json:"organizer_id"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Province,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.Capacity,
		arg.Description,
		arg.OrganizerID,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Province,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Capacity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
